[package]
name = "file_encryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
eframe = "0.22"        
egui = "0.22"
aes = "0.7"
block-modes = "0.8"
rand = "0.8"
simplelog = "0.12.0"

[dependencies.winapi]
version = "0.3"
features = ["winuser", "windef"]